### ISSUE TITLE
Header Animation video stops playing @1:10

### ISSUE THREAD

**Issue by bobate** [ByteGrad/CSS-Course#1]
Header Animation video stops playing @1:10
It's stuck at that point, and clicking forward does not display further content so I can't see the code you're using. I haven't looked in the files here on github yet, but I really want to watch/hear you put it all together and explain it all, so hopefully you can repair that video. Thanks. Great demonstrations so far.

**Comment by ByteGrad** [comment]
Hi, thanks for telling me.

I just checked and the problem seems to be resolved.

What seems to happen sometimes is that the CDN can be a bit slow if the network is ‘cold’, e.g. the last time someone watched this video was 2 hours ago. These CDNs probably expect much more traffic.

**Comment by bobate** [comment]
Whatever was the cause of the problem, which has happened again numerous times and still happening occasionally, I found that if I simply copy the episode's URL, close the stalled tab, and paste the URL to a new tab, it runs fine. Merely refreshing the page didn't resolve it.
So it seemed to happen after I took too long a break from working on it, so your 'cold' theory sounds right.

**Comment by ByteGrad** [comment]
Interesting that it keeps happening. I'll keep monitoring this to see if it remains a problem. Apologies for the inconvenience in any case.

**Comment by ByteGrad** [comment]
I think I finally figured out what it was.

The videos are 1080p (Full HD) as a default. This gives the highest quality, but even on decent Internet connections you will still suffer from annoying buffering/stalling sometimes.

I've updated the course dashboard now to improve several things, among them being the option to downgrade the video quality to 720p (HD) and 540p (SD) for increased speed.
