### ISSUE TITLE
Small Header Issue

### ISSUE THREAD

**Issue by ronnieross711** [ByteGrad/CSS-Course#2]
Class is great and everything has gone smoothly and I am learning a lot. The only issue I am having is that the header doesn't span the entirety of the web page. I have looked and looked and looked for the problem. Could be a simple typo and I just can't find it. But I have no issues in my console so it appears that everything is working.  It's like google chrome doesn't like the background-image linear gradient in the .header tag. Thanks in advance for your help.

/*----html----*/

`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="icon" type="image/png" href="https://bytegrad.com/course-assets/css/1/favicon.png">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/lato-font/3.0.0/css/lato-font.min.css" integrity="sha512-rSWTr6dChYCbhpHaT1hg2tf4re2jUxBWTuZbujxKg96+T87KQJriMzBzW5aqcb8jmzBhhNSx4XYGA6/Y+ok1vQ==" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA==" crossorigin="anonymous">
    <link rel="stylesheet" href="style.css">

    <title>SocialEditor -- Simple editor to create and publish social media posts</title>
</head>
<body class="app">

    <header class="header">
        <img src="https://bytegrad.com/course-assets/css/1/logo.svg" alt="logo" class="logo">
        <button class="dd-toggle">File</button>
        <button class="dd-toggle">View</button>
        <button class="dd-toggle">New</button>
        <button class="dd-toggle">
            <i class="fas fa-crown dd-toggle__icon"></i>
        </button>
        <button class="dd-toggle">
            <i class="fas fa-bell dd-toggle__icon"></i>
        </button>
        <button class="dd-toggle">
            <img src="https://images.unsplash.com/photo-1614247484197-9c6164bb532f?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&fit=crop&w=60&q=100" alt="User photo" class="dd-toggle__img">
            <span class="dd-toggle__text">James O.</span>
        </button>
    </header>

    <div class="app__container">
        <div class="sidebar">
            <section class="menu">
                <button class="menu__button">
                    <i class="fas fa-layer-group menu__icon"></i>
                    <span class="menu__text">Templates</span>
                </button>
                <button class="menu__button menu__button--active">
                    <i class="fas fa-image menu__icon"></i>
                    <span class="menu__text">Images</span>
                </button>
                <button class="menu__button">
                    <i class="fas fa-font menu__icon"></i>
                    <span class="menu__text">Text/Font</span>
                </button>
                <button class="menu__button">
                    <i class="fas fa-shapes menu__icon"></i>
                    <span class="menu__text">Shapes</span>
                </button>
            </section>

            <footer class="footer">
                <small class="copyright">&copy; 2050 SocialEditor. All rights reserved.</small>
            </footer>
        </div>

        <section class="panel">
            <div class="panel__top">
                <h1 class="first-heading">Images</h1>
                <i class="fas fa-angle-double-left panel__collapse-icon"></i>
            </div>
            <div class="panel__images">
                <img class="panel__img" src="https://images.unsplash.com/photo-1543096222-72de739f7917?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&fit=crop&w=280&q=100" alt="Uploaded image">
                <img class="panel__img" src="https://images.unsplash.com/photo-1475598322381-f1b499717dda?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&fit=crop&h=280&q=100" alt="Uploaded image">
                <img class="panel__img" src="https://images.unsplash.com/photo-1615887023516-9b6bcd559e87?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&fit=crop&w=280&q=100" alt="Uploaded image">
                <img class="panel__img" src="https://images.unsplash.com/photo-1615749190340-34c7c3b16784?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&fit=crop&w=280&q=100" alt="Uploaded image">
                <img class="panel__img" src="https://images.unsplash.com/photo-1615707547992-93435f1e7f13?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&fit=crop&w=280&q=100" alt="Uploaded image">
                <button class="panel__btn">
                    <i class="fas fa-plus panel__upload-icon"></i>
                </button>
            </div>
        </section>

        <main class="main">
            <div class="info-bar">
                <section class="breadcrumbs">
                    <a href="#" class="breadcrumbs__link">Facebook posts</a>
                    <i class="fas fa-angle-right breadcrumbs__icon"></i>
                    <span class="breadcrumbs__name">Happy-hour-friday</span>
                </section>
                <button class="button">Publish</button>
            </div>

            <div class="artboard">
                <section class="canvas">
                    <img class="canvas__bg-img" src="https://images.unsplash.com/photo-1615887023516-9b6bcd559e87?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&fit=crop&w=2134&q=100" alt="Background image">
                    <img class="canvas__fg-img" src="https://images.unsplash.com/photo-1615887023516-9b6bcd559e87?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&fit=crop&w=1453&q=85" alt="Foreground image">
                    <div class="canvas__circle"></div>
                    <div class="canvas__circle"></div>
                    <div class="canvas__circle"></div>
                    <div class="canvas__circle"></div>
                </section>
                <section class="tools">
                    <button class="tool tool--active">
                        <i class="fas fa-crop-alt tool__icon"></i>
                    </button>
                    <button class="tool">
                        <i class="fas fa-object-group tool__icon"></i>
                    </button>
                    <button class="tool">
                        <i class="fas fa-pen tool__icon"></i>
                    </button>
                    <button class="tool">
                        <i class="fas fa-trash tool__icon"></i>
                    </button>
                </section>
            </div>
        </main>
    </div>
    
</body>
</html>`

/*----CSS----*/

`/* RESET */
* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}
/* take away default boarders and background of css for all buttons */
button {
    border: initial;
    background-color: initial;
    color: inherit;        /* All buttons will inherit the .app color and font*/
    font: inherit;
    outline: none; /* make sure there is a visual indicator for focus state */
}

/* KEYFRAMES */
/* The keyframes is the animation that is happening to the navbar/header */
@keyframes fade-in-from-top {
    0% {
        opacity: 0;
        transform: translateY(-50px);
    }

    100% {
        opacity: 1;
        transform: translateY(0px);
    }
}

@keyframes fade-in-from-left {
    0% {
        opacity: 0;
        transform: translateX(-50px);
    }

    100% {
        opacity: 1;
        transform: translateX(0px);
    }
}

@keyframes fade-in {
    0% {
        opacity: 0;
    }
    100% {
        opacity: 1;
    }
}

/* BASE STYLES */
.app {
    font-family: 'Lato', sans-serif;
    font-size: 15px;
    color: #fff;
    height: 100vh;
    width: 100vh;

}

.app__container {
    height: calc(100vh - 55px);
    display: flex;
}

/* STYLES */
.header {
        background-image: linear-gradient(to right, #18A0BE, #622DB9);
        height: 55px;
        display: flex; 
        /* creates a flex container for everything in header */
}

.logo {
    align-self: center;
    margin-left: 20px;
    margin-right: 30px;
    animation: fade-in-from-top 0.5s;
}

.dd-toggle {
    color: rgba(255, 255, 255, 0.7);
    padding: 0 13px;
    cursor: pointer;
    transition: all 0.4s;
    animation: fade-in-from-top 0.5s;
}

.dd-toggle:hover {
    color: #fff;
    background-color: rgba(255, 255, 255, 0.07);
}

.dd-toggle:focus {
    color: #fff;
    background-color: rgba(255, 255, 255, 0.07);
}

.dd-toggle:nth-of-type(4) {
    margin-left: auto;
}

.dd-toggle:Last-child {
    display: flex;
    align-items: center;
}

.dd-toggle__icon {

}

.dd-toggle__img {
    height: 30px;
    width: 30px;
    object-fit: cover;   /* Best practice for images so the image isn't distorted*/
    border-radius: 50%;
    margin-right: 7px;
}

.dd-toggle__text {

}

/* SIDEBAR */

.sidebar {
    background-color: #10171A;
    width: 75px;
    display: flex;
    flex-direction: column;
}

.menu {

}

.menu__button {
    padding: 19px 0;
    color: rgba(255, 255, 255, 0.4);
    display: flex;
    flex-direction: column;
    align-items: center;
    width: 100%;
    transition: all 0.4s;
    animation: fade-in-from-left 0.5s;
}

.menu__button:hover {
    background-color: #2B363B;
    color: #fff;
    cursor: pointer;
}

.menu__button:focus {
    background-color: #2B363B;
    color: #fff;
    cursor: pointer;
}

.menu__button--active {
    background-color: #2B363B;
    color: #fff;
    position: relative;
}

.menu__button--active::before {
    content: '';
    width: 3px;
    height: 100%;
    background-color: #375BB6;
    position: absolute;
    left: 0;
    top: 0;
}

.menu__icon {
    font-size: 18px;
    margin-bottom: 3px;
}

.menu__text {
    font-weight: 500;
    font-size: 12px;
}

.footer {
    margin-top: auto;
    margin-bottom: 60px;
    transform: rotate(-90deg);

}

.copyright {
    color: rgba(255, 255, 255, 0.15);
    font-size: 12px;
    white-space: nowrap;
}

/* PANEL */

.panel {
    background-color: #2B363C;
    width: 350px;
    padding: 15px 31px;
}

.panel__top {
    display: flex;
    align-items: center;
    justify-content: space-between;
    border-bottom: 1px solid #4b5155;
    padding-bottom: 12px;
}

.first-heading {
    font-size: 18px;
    font-weight: 400;
}

.panel__collapse-icon {
    color: #6b7276;
    cursor: pointer;
}

.panel__images {
    padding: 25px 0;
    display: flex;
    flex-wrap: wrap;
    gap: 8px;  /* creates space between the rows and gaps */
}

.panel__img {
    width: 140px;
    height: 140px;
    object-fit: cover;  /* good practice for images so images don't distort after adding width and height */
    border-radius: 7px;
    cursor: pointer;
    transition: all 0.2s;
    animation: fade-in 1s;
}

.panel__img:nth-child(2) {
    animation: fade-in 1s 0.1s backwards;
}

.panel__img:nth-child(3) {
    animation: fade-in 1s 0.2s backwards;
}

.panel__img:nth-child(4) {
    animation: fade-in 1s 0.3s backwards;
}

.panel__img:hover {
    transform: scale(1.05);
}

.panel__btn {
    width: 140px;
    height: 140px;
    border-radius: 7px;
    background-color: #333e44;
    cursor: pointer;
    transition: all 0.2s;
    animation: fade-in 1s 0.5s backwards;
}

.panel__btn:hover,
.panel__btn:focus {
    background-color: #404c52;
    
}

.panel__upload-icon {
    font-size: 25px;
    color: #21292d;
}

/* MAIN CONTENT */

.main {
    background-color: #EDF1F3;
    flex: 1;
}

.info-bar {
    height: 50px;
    background-color: #fff;
    border-bottom: 1px solid #D6DDE1;
    padding: 0 30px;
    display: flex;
    align-items: center;
    justify-content: space-between;
}

.breadcrumbs {
    text-transform: uppercase;
    letter-spacing: 0.5px;
    font-size: 12px;
}

.breadcrumbs__link {
    color: #A6ADB1;
    text-decoration: none;
}

.breadcrumbs__icon {
    color: #A6ADB1;
    margin: 0 13px;
}

.breadcrumbs__name {
    color: #2E3335;
    font-weight: 500;
}

.button {
    background-color: #375BB6;
    font-size: 11px;
    text-transform: uppercase;
    letter-spacing: 1px;
    padding: 8px 20px;
    cursor: pointer;
    border-radius: 500px;
    transition: all 0.4s;
}

.button:hover, 
button:focus {
    background-color: #26438D;
}

.artboard {
    height: calc(100vh - 50px - 55px);
    display: flex;
    justify-content: center;
    align-items: center;
    margin-top: -25px;
    column-gap: 20px;
}

.canvas {
    height: 57.5vh; /* viewPort hieght */
    width: 48.6vw;  /* viewPort width */
    position: relative;
    border: 1px solid #fff;
    border-radius: 3px;
}

.canvas__bg-img {
    height: 100%;
    width: 100%;
    object-fit: cover;
    opacity: 0.15;
}

.canvas__fg-img {
    height: 75%;
    width: 78%;
    object-fit: cover;
    border-radius: 3px;
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);  /* -50% makes the image relative to its own size */
    border: 1px solid #fff;
    cursor: grab;

}

.canvas__cirlce {
    height: 15px;
    width: 15px;
    border-radius: 50%;
    background-color: #fff;
    position: absolute;
}

.canvas__cirlce:nth-of-type(1) {
    top: 11.5%;
    left: 10.4%;
    cursor: nw-resize;
}

.canvas__cirlce:nth-of-type(2) {
    top: 11.5%;
    right: 10.4%;
    cursor: sw-resize;
}

.canvas__cirlce:nth-of-type(3) {
    bottom: 11.5%;
    left: 10.4%;
    cursor: nw-resize;
}

.canvas__cirlce:nth-of-type(4) {
    bottom: 11.5%;
    right: 10.4%;
    cursor: sw-resize;
}

.tools {
    height: 57.5vh;
    display: flex;
    flex-direction: column;
}

.tool {
    background-color: #E1E6E9;
    height: 44px;
    width: 44px;
    border-radius: 8px;
    color: #404446;
    cursor: pointer;
}

.tool--active {
    background-color: #2B636B;
    color: #fff;
}

.tool:Last-child {
    margin-top: auto;
}

.tool__icon {

}`

**Comment by ronnieross711** [comment]
[scrrenshot-pdf.pdf](https://github.com/ByteGrad/CSS-Course/files/7764804/scrrenshot-pdf.pdf)

**Comment by ByteGrad** [comment]
Hi Ronnie,

I just copy-pasted your code in my editor to try it out and the header seems to stretch all the way. It looks just like it is supposed to on my screen.

There seems to be another issue on the right side as well as the rest is not taking up any space over there either.

Probably best to simply copy+paste all the final code of the video where you are stuck at. Every video has a folder with the complete final code in this repository.

**Comment by ronnieross711** [comment]
Cool man thank you. Yea I tried that and it obviously worked. I just didn’t
know if it was something on my end. I’m going to try a hard restart of my
computer and see if that changes anything. Really you’re teaching me
concepts about CSS so as long as I understand what you’re teaching that’s
all that matters.

**Comment by ByteGrad** [comment]
Yeah can be unsatisfying not knowing what caused the problem. I do a deep dive if it's a problem that happens multiple times, otherwise I just accept I'm not going to know the exact cause every time and move on.
