### ISSUE TITLE
Problem with Project1 Notes

### ISSUE THREAD

**Issue by gizmola** [ByteGrad/CSS-Course#3]
Honestly, _great course_.  

On the SocialEditor project, your image links in the notes section for the "Panel" have the wrong class.  When instructed to copy/paste from those notes, anyone following along will have an issue.  The links have class "images__img" and it should be "panel__img".

![socialEditor-notes-bug](https://user-images.githubusercontent.com/947890/149651305-3c68d610-66be-426e-a915-50a729d2a3e7.jpg)

**Comment by ByteGrad** [comment]
Great catch, I fixed it.

Thanks a lot for telling me and great to hear you like the course!
