### ISSUE TITLE
A gallery image in BetterPhotos is no longer at that address

### ISSUE THREAD

**Issue by jloboguapo** [ByteGrad/CSS-Course#5]
This is the link:

https://images.unsplash.com/photo-1611599361713-17db15c39691?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&fit=crop&h=416&q=100

**Comment by ByteGrad** [comment]
Thanks! Fixed.
