### ISSUE TITLE
Right attribute value for Favicon

### ISSUE THREAD

**Issue by madhavanand-github** [ByteGrad/CSS-Course#8]
To insert favicon, we use `link` tag

We can use both below mentioned value to attribute `rel`

1.  `rel = "icon"`
2.  `rel = "shortcut icon"`

Which one is **recommended** and what's the **difference** ?

**Comment by ByteGrad** [comment]
Hi Madhav,

I don’t think there is a difference. Also, I don’t think this matters;
there are millions of little details that you could focus on but best to
focus on the important stuff.

Good luck with the course!

**Comment by madhavanand-github** [comment]
`There are millions of little details that you could focus on, but best to
focus on the important stuff.`

That's the best advice. Loved it.
Thanks for your quick response.
